### ISSUE TITLE
Fix "100% Volunteer Run" Tag on Website

### ISSUE THREAD

**Issue by abelsonlive** [bushwickayudamutua/bushwickayudamutua.github.io#18]
The CSS is off on this tag on the homepage:

![Image](https://user-images.githubusercontent.com/1621721/235234435-748dbc5b-9bd1-4eca-b1df-c88a25d667a9.png)

**Comment by vishalsingh2972** [comment]
Hey @abelsonlive can you assign this to me? Also, I am a beginner so could you please help me in locating the file in which changes need to be made!

**Comment by AliaElKattan** [comment]
should be fixed!

<img width="1512" alt="image" src="https://github.com/bushwickayudamutua/bushwickayudamutua.github.io/assets/7271371/5228b58a-309c-45c2-a281-87444b0bdcbc">

**Comment by AliaElKattan** [comment]
should be fixed!

<img width="1512" alt="image" src="https://github.com/bushwickayudamutua/bushwickayudamutua.github.io/assets/7271371/77736f55-1cd1-49c8-b6ad-300de23a69d4">
