### ISSUE TITLE
Fix sizing of homepage image carousel

### ISSUE THREAD

**Issue by abelsonlive** [bushwickayudamutua/bushwickayudamutua.github.io#19]
The image carousel on the homepage is too large. it's especially bad on mobile.

![Image](https://user-images.githubusercontent.com/1621721/235234824-baa987fa-4db6-4b97-919b-c5a31ac65aa9.png)

![Image](https://user-images.githubusercontent.com/1621721/235234816-760e9584-7256-4157-9562-9291fd50bdcf.png)

**Comment by naim16031988** [comment]
hello, this website looks amazing, but unfortunately it is written with some software that make it hard to fixe.
there is no css file to design as you want. this is just my opinion and i am just a learner

**Comment by AliaElKattan** [comment]
should be fixed!

<img width="1512" alt="image" src="https://github.com/bushwickayudamutua/bushwickayudamutua.github.io/assets/7271371/f2a4bb23-74ec-4471-8c50-f6e87003a355">

**Comment by AliaElKattan** [comment]
replaced carousel

<img width="1512" alt="image" src="https://github.com/bushwickayudamutua/bushwickayudamutua.github.io/assets/7271371/68185b7c-a792-4d34-b92c-facd3789d68a">
